### ISSUE TITLE
Missing #desc key in ephemeris when importing OCS2 programs

### ISSUE THREAD

**Issue by jdnavarro** [gemini-hlsw/gem#268]
@swalker2m mentions some of the old programs have nonsidereal targets but no horizons key. Those are supposed to be filtered out though.

```
java.lang.RuntimeException: Problem parsing GN-2017A-Q-63.xml: MissingKey(\! #des)
	at scala.sys.package$.error(package.scala:27)
	at gem.ocs2.FileImporter$.$anonfun$readAndInsert$1(FileImporter.scala:53)
	at cats.effect.internals.IORunLoop$.liftedTree3$1(IORunLoop.scala:194)
	at cats.effect.internals.IORunLoop$.step(IORunLoop.scala:194)
	at cats.effect.IO.unsafeRunTimed(IO.scala:222)
	at cats.effect.IO.unsafeRunSync(IO.scala:175)
	at gem.ocs2.FileImporter$.main(FileImporter.scala:78)
	at gem.ocs2.FileImporter.main(FileImporter.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:93)
	at sbt.Run.run0(Run.scala:87)
	at sbt.Run.execute$1(Run.scala:65)
	at sbt.Run.$anonfun$run$4(Run.scala:77)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at sbt.util.InterfaceUtil$$anon$1.get(InterfaceUtil.scala:10)
	at sbt.TrapExit$App.run(TrapExit.scala:252)
	at java.lang.Thread.run(Thread.java:748)
```

GN-2017B-Q-77 also gives this error.

**Comment by swalker2m** [comment]
Here is [the filtering](https://github.com/gemini-hlsw/gem/blob/master/modules/ocs2/src/main/scala/gem/ocs2/Decoders.scala#L176-L193) I mentioned. Perhaps there is an horizons designation, but it is missing something.
