### ISSUE TITLE
Telescope Offset Import Problem

### ISSUE THREAD

**Issue by swalker2m** [gemini-hlsw/gem#79]
There are random import failures that I believe are related to offset p/q in science steps.  I wonder if it has to do with the recent conversion of `Angle` to store integral value.

```
org.postgresql.util.PSQLException: ERROR: numeric field overflow
  Detail: A field with precision 9, scale 3 must round to an absolute value less than 10^6.
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2476)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2189)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:169)
	at org.postgresql.jdbc.PgPreparedStatement.executeUpdate(PgPreparedStatement.java:136)
	at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeUpdate$5(kleisliinterpreter.scala:646)
	at doobie.free.KleisliInterpreter$PreparedStatementInterpreter.$anonfun$executeUpdate$5$adapted(kleisliinterpreter.scala:646)
	at doobie.free.KleisliInterpreter.$anonfun$primitive$2(kleisliinterpreter.scala:103)
	at scalaz.effect.IO$.$anonfun$apply$2(IO.scala:178)
	at scalaz.std.FunctionInstances$$anon$1.$anonfun$map$1(Function.scala:77)
	at scalaz.Free.$anonfun$run$1(Free.scala:271)
	at scalaz.Free.go2$1(Free.scala:162)
	at scalaz.Free.go(Free.scala:165)
	at scalaz.Free.run(Free.scala:271)
	at scalaz.effect.IO.$anonfun$except$1(IO.scala:71)
	at scalaz.effect.IO$$anon$7.$anonfun$apply$5(IO.scala:236)
	at scalaz.std.FunctionInstances$$anon$1.$anonfun$map$1(Function.scala:77)
	at scalaz.Free.$anonfun$run$1(Free.scala:271)
	at scalaz.Free.go2$1(Free.scala:162)
	at scalaz.Free.go(Free.scala:165)
	at scalaz.Free.run(Free.scala:271)
	at scalaz.effect.IO.$anonfun$except$1(IO.scala:71)
	at scalaz.effect.IO$$anon$7.$anonfun$apply$5(IO.scala:236)
	at scalaz.std.FunctionInstances$$anon$1.$anonfun$map$1(Function.scala:77)
	at scalaz.Free.$anonfun$run$1(Free.scala:271)
	at scalaz.Free.go2$1(Free.scala:162)
	at scalaz.Free.go(Free.scala:165)
	at scalaz.Free.run(Free.scala:271)
	at scalaz.effect.IO.$anonfun$except$1(IO.scala:71)
	at scalaz.effect.IO$$anon$7.$anonfun$apply$5(IO.scala:236)
	at scalaz.std.FunctionInstances$$anon$1.$anonfun$map$1(Function.scala:77)
	at scalaz.Free.$anonfun$run$1(Free.scala:271)
	at scalaz.Free.go2$1(Free.scala:162)
	at scalaz.Free.go(Free.scala:165)
	at scalaz.Free.run(Free.scala:271)
	at scalaz.effect.IO.$anonfun$except$1(IO.scala:71)
	at scalaz.effect.IO$$anon$7.$anonfun$apply$5(IO.scala:236)
	at scalaz.std.FunctionInstances$$anon$1.$anonfun$map$1(Function.scala:77)
	at scalaz.Free.$anonfun$run$1(Free.scala:271)
	at scalaz.Free.go2$1(Free.scala:162)
	at scalaz.Free.go(Free.scala:165)
	at scalaz.Free.run(Free.scala:271)
	at scalaz.effect.IO.$anonfun$except$1(IO.scala:71)
	at scalaz.effect.IO$$anon$7.$anonfun$apply$5(IO.scala:236)
	at scalaz.std.FunctionInstances$$anon$1.$anonfun$map$1(Function.scala:77)
	at scalaz.Free.$anonfun$run$1(Free.scala:271)
	at scalaz.Free.go2$1(Free.scala:162)
	at scalaz.Free.go(Free.scala:165)
	at scalaz.Free.run(Free.scala:271)
	at scalaz.effect.IO.$anonfun$except$1(IO.scala:71)
	at scalaz.effect.IO$$anon$7.$anonfun$apply$5(IO.scala:236)
	at scalaz.std.FunctionInstances$$anon$1.$anonfun$map$1(Function.scala:77)
	at scalaz.Free.$anonfun$run$1(Free.scala:271)
	at scalaz.Free.go2$1(Free.scala:162)
	at scalaz.Free.go(Free.scala:165)
	at scalaz.Free.run(Free.scala:271)
	at scalaz.effect.IO.$anonfun$except$1(IO.scala:71)
	at scalaz.effect.IO$$anon$7.$anonfun$apply$5(IO.scala:236)
	at scalaz.std.FunctionInstances$$anon$1.$anonfun$map$1(Function.scala:77)
	at scalaz.Free.$anonfun$run$1(Free.scala:271)
	at scalaz.Free.go2$1(Free.scala:162)
	at scalaz.Free.go(Free.scala:165)
	at scalaz.Free.run(Free.scala:271)
	at scalaz.effect.IO.unsafePerformIO(IO.scala:22)
	at scalaz.effect.SafeApp.main(SafeApp.scala:20)
	at scalaz.effect.SafeApp.main$(SafeApp.scala:19)
	at gem.ocs2.FileImporter$.main(FileImporter.scala:28)
	at gem.ocs2.FileImporter.main(FileImporter.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sbt.Run.invokeMain(Run.scala:67)
	at sbt.Run.run0(Run.scala:61)
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51)
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55)
	at sbt.Logger$$anon$4.apply(Logger.scala:84)
	at sbt.TrapExit$App.run(TrapExit.scala:248)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tpolecat** [comment]
The only angle we're storing right now is p/q offsets which we store as signed decimal arcseconds. I may have gotten the scaling backwards. I'll check. Do you know offhand which value was being stored when this happened?

**Comment by tpolecat** [comment]
Yeah I did it wrong. PR incoming.

**Comment by swalker2m** [comment]
Something seems wrong.  I wouldn't expect a subarcsec offset.
```
gem=# select * from step_science where offset_p != 0.0;
 step_science_id |  offset_p  |  offset_q  
-----------------+------------+------------
           16486 | 648000.000 |      0.000
           16489 | 648000.000 |      0.000
           16490 | 648000.000 |      0.000
           16493 | 648000.000 |      0.000
           16497 | 648000.000 |      0.000
           16500 | 648000.000 |      0.000
           16501 | 648000.000 |      0.000
           16504 | 648000.000 |      0.000
           22136 | 648000.000 |      0.000
           22139 | 648000.000 |      0.000
           22140 | 648000.000 |      0.000
           22143 | 648000.000 |      0.000
           23239 | 518400.000 | 777600.000
           23240 | 518400.000 | 648000.000
           23241 | 518400.000 | 388800.000
           23270 | 518400.000 | 777600.000
           23271 | 518400.000 | 648000.000
           23272 | 518400.000 | 388800.000
```
